dist: xenial
virt: lxd
os: linux

vm:
  size:
    - x-large

env:
  - CI=false TERM=xterm

before_install:
  - git checkout $TRAVIS_BRANCH

install: 
  - pwd 
  - ls
  
script:
  - grep MemTotal /proc/meminfo
