jobs:
  include:
    # No VM size defined - uses the default 2vCPU and RAM
    - stage: No VM Size Defined
      os: linux
      dist: focal
      language: ruby
      script:
        - free -m
    # VM size large defined
    - stage: Large VM Size Defined
      os: linux
      dist: focal
      language: ruby
      vm:
        size:
          - large
      script:
        - free -m
    # VM size x-large defined
    - stage: X-Large VM Size Defined
      os: linux
      dist: focal
      language: ruby
      vm:
        size:
          - x-large
      script:
        - free -m
